-- CreateTable
CREATE TABLE "Plant" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "common_name" TEXT NOT NULL,
    "scientific_name" JSONB,
    "other_name" JSONB,
    "family" TEXT NOT NULL,
    "hybrid" TEXT,
    "subspecies" TEXT,
    "cultivar" TEXT,
    "variety" TEXT,
    "species_epithet" TEXT,
    "genus" TEXT NOT NULL,
    "origin" JSONB NOT NULL,
    "type" TEXT NOT NULL,
    "dimensions" JSONB,
    "cycle" TEXT NOT NULL,
    "attracts" TEXT,
    "propagation" JSONB,
    "hardiness" JSONB NOT NULL,
    "watering" TEXT NOT NULL,
    "watering_general_benchmark" JSONB,
    "plant_anatomy" JSONB,
    "pruning_month" JSONB,
    "seeds" BOOLEAN,
    "maintenance" TEXT,
    "soil" JSONB,
    "growth_rate" TEXT,
    "drought_tolerant" BOOLEAN,
    "salt_tolerant" BOOLEAN,
    "thorny" BOOLEAN,
    "invasive" BOOLEAN,
    "tropical" BOOLEAN,
    "indoor" BOOLEAN,
    "care_level" TEXT,
    "pest_susceptibility" JSONB,
    "flowers" BOOLEAN,
    "flowering_season" TEXT,
    "cones" BOOLEAN,
    "fruits" BOOLEAN,
    "edible_fruit" BOOLEAN,
    "harvest_season" TEXT NOT NULL,
    "leaf" BOOLEAN,
    "edible_leaf" BOOLEAN,
    "cuisine" BOOLEAN,
    "medicinal" BOOLEAN,
    "poisonous_to_humans" BOOLEAN,
    "poisonous_to_pets" BOOLEAN,
    "description" TEXT NOT NULL,
    "default_image" JSONB
);
